// Generated by gencpp from file pepper_talk/Say.msg
// DO NOT EDIT!


#ifndef PEPPER_TALK_MESSAGE_SAY_H
#define PEPPER_TALK_MESSAGE_SAY_H

#include <ros/service_traits.h>


#include <pepper_talk/SayRequest.h>
#include <pepper_talk/SayResponse.h>


namespace pepper_talk
{

struct Say
{

typedef SayRequest Request;
typedef SayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Say
} // namespace pepper_talk


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::pepper_talk::Say > {
  static const char* value()
  {
    return "744b6fa2f5c40325431e2e62fe3a175f";
  }

  static const char* value(const ::pepper_talk::Say&) { return value(); }
};

template<>
struct DataType< ::pepper_talk::Say > {
  static const char* value()
  {
    return "pepper_talk/Say";
  }

  static const char* value(const ::pepper_talk::Say&) { return value(); }
};


// service_traits::MD5Sum< ::pepper_talk::SayRequest> should match
// service_traits::MD5Sum< ::pepper_talk::Say >
template<>
struct MD5Sum< ::pepper_talk::SayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_talk::Say >::value();
  }
  static const char* value(const ::pepper_talk::SayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_talk::SayRequest> should match
// service_traits::DataType< ::pepper_talk::Say >
template<>
struct DataType< ::pepper_talk::SayRequest>
{
  static const char* value()
  {
    return DataType< ::pepper_talk::Say >::value();
  }
  static const char* value(const ::pepper_talk::SayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::pepper_talk::SayResponse> should match
// service_traits::MD5Sum< ::pepper_talk::Say >
template<>
struct MD5Sum< ::pepper_talk::SayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::pepper_talk::Say >::value();
  }
  static const char* value(const ::pepper_talk::SayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::pepper_talk::SayResponse> should match
// service_traits::DataType< ::pepper_talk::Say >
template<>
struct DataType< ::pepper_talk::SayResponse>
{
  static const char* value()
  {
    return DataType< ::pepper_talk::Say >::value();
  }
  static const char* value(const ::pepper_talk::SayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PEPPER_TALK_MESSAGE_SAY_H
