// Generated by gencpp from file detection_srv/DetectorResponse.msg
// DO NOT EDIT!


#ifndef DETECTION_SRV_MESSAGE_DETECTORRESPONSE_H
#define DETECTION_SRV_MESSAGE_DETECTORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace detection_srv
{
template <class ContainerAllocator>
struct DetectorResponse_
{
  typedef DetectorResponse_<ContainerAllocator> Type;

  DetectorResponse_()
    : objects()  {
    }
  DetectorResponse_(const ContainerAllocator& _alloc)
    : objects(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > , typename ContainerAllocator::template rebind<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::other >  _objects_type;
  _objects_type objects;





  typedef boost::shared_ptr< ::detection_srv::DetectorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::detection_srv::DetectorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct DetectorResponse_

typedef ::detection_srv::DetectorResponse_<std::allocator<void> > DetectorResponse;

typedef boost::shared_ptr< ::detection_srv::DetectorResponse > DetectorResponsePtr;
typedef boost::shared_ptr< ::detection_srv::DetectorResponse const> DetectorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::detection_srv::DetectorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::detection_srv::DetectorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::detection_srv::DetectorResponse_<ContainerAllocator1> & lhs, const ::detection_srv::DetectorResponse_<ContainerAllocator2> & rhs)
{
  return lhs.objects == rhs.objects;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::detection_srv::DetectorResponse_<ContainerAllocator1> & lhs, const ::detection_srv::DetectorResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace detection_srv

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::detection_srv::DetectorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::detection_srv::DetectorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_srv::DetectorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::detection_srv::DetectorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_srv::DetectorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::detection_srv::DetectorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::detection_srv::DetectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "39d6292ea712a13252ebdb5470ba0086";
  }

  static const char* value(const ::detection_srv::DetectorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x39d6292ea712a132ULL;
  static const uint64_t static_value2 = 0x52ebdb5470ba0086ULL;
};

template<class ContainerAllocator>
struct DataType< ::detection_srv::DetectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "detection_srv/DetectorResponse";
  }

  static const char* value(const ::detection_srv::DetectorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::detection_srv::DetectorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string[] objects\n"
;
  }

  static const char* value(const ::detection_srv::DetectorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::detection_srv::DetectorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.objects);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DetectorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::detection_srv::DetectorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::detection_srv::DetectorResponse_<ContainerAllocator>& v)
  {
    s << indent << "objects[]" << std::endl;
    for (size_t i = 0; i < v.objects.size(); ++i)
    {
      s << indent << "  objects[" << i << "]: ";
      Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.objects[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // DETECTION_SRV_MESSAGE_DETECTORRESPONSE_H
