// Generated by gencpp from file detection_srv/Detector.msg
// DO NOT EDIT!


#ifndef DETECTION_SRV_MESSAGE_DETECTOR_H
#define DETECTION_SRV_MESSAGE_DETECTOR_H

#include <ros/service_traits.h>


#include <detection_srv/DetectorRequest.h>
#include <detection_srv/DetectorResponse.h>


namespace detection_srv
{

struct Detector
{

typedef DetectorRequest Request;
typedef DetectorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Detector
} // namespace detection_srv


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::detection_srv::Detector > {
  static const char* value()
  {
    return "39d6292ea712a13252ebdb5470ba0086";
  }

  static const char* value(const ::detection_srv::Detector&) { return value(); }
};

template<>
struct DataType< ::detection_srv::Detector > {
  static const char* value()
  {
    return "detection_srv/Detector";
  }

  static const char* value(const ::detection_srv::Detector&) { return value(); }
};


// service_traits::MD5Sum< ::detection_srv::DetectorRequest> should match
// service_traits::MD5Sum< ::detection_srv::Detector >
template<>
struct MD5Sum< ::detection_srv::DetectorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::detection_srv::Detector >::value();
  }
  static const char* value(const ::detection_srv::DetectorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::detection_srv::DetectorRequest> should match
// service_traits::DataType< ::detection_srv::Detector >
template<>
struct DataType< ::detection_srv::DetectorRequest>
{
  static const char* value()
  {
    return DataType< ::detection_srv::Detector >::value();
  }
  static const char* value(const ::detection_srv::DetectorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::detection_srv::DetectorResponse> should match
// service_traits::MD5Sum< ::detection_srv::Detector >
template<>
struct MD5Sum< ::detection_srv::DetectorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::detection_srv::Detector >::value();
  }
  static const char* value(const ::detection_srv::DetectorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::detection_srv::DetectorResponse> should match
// service_traits::DataType< ::detection_srv::Detector >
template<>
struct DataType< ::detection_srv::DetectorResponse>
{
  static const char* value()
  {
    return DataType< ::detection_srv::Detector >::value();
  }
  static const char* value(const ::detection_srv::DetectorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DETECTION_SRV_MESSAGE_DETECTOR_H
