// Generated by gencpp from file move_head/Head_position.msg
// DO NOT EDIT!


#ifndef MOVE_HEAD_MESSAGE_HEAD_POSITION_H
#define MOVE_HEAD_MESSAGE_HEAD_POSITION_H

#include <ros/service_traits.h>


#include <move_head/Head_positionRequest.h>
#include <move_head/Head_positionResponse.h>


namespace move_head
{

struct Head_position
{

typedef Head_positionRequest Request;
typedef Head_positionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Head_position
} // namespace move_head


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::move_head::Head_position > {
  static const char* value()
  {
    return "c55b3b2c584945fab7834a7633541610";
  }

  static const char* value(const ::move_head::Head_position&) { return value(); }
};

template<>
struct DataType< ::move_head::Head_position > {
  static const char* value()
  {
    return "move_head/Head_position";
  }

  static const char* value(const ::move_head::Head_position&) { return value(); }
};


// service_traits::MD5Sum< ::move_head::Head_positionRequest> should match
// service_traits::MD5Sum< ::move_head::Head_position >
template<>
struct MD5Sum< ::move_head::Head_positionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::move_head::Head_position >::value();
  }
  static const char* value(const ::move_head::Head_positionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_head::Head_positionRequest> should match
// service_traits::DataType< ::move_head::Head_position >
template<>
struct DataType< ::move_head::Head_positionRequest>
{
  static const char* value()
  {
    return DataType< ::move_head::Head_position >::value();
  }
  static const char* value(const ::move_head::Head_positionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::move_head::Head_positionResponse> should match
// service_traits::MD5Sum< ::move_head::Head_position >
template<>
struct MD5Sum< ::move_head::Head_positionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::move_head::Head_position >::value();
  }
  static const char* value(const ::move_head::Head_positionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::move_head::Head_positionResponse> should match
// service_traits::DataType< ::move_head::Head_position >
template<>
struct DataType< ::move_head::Head_positionResponse>
{
  static const char* value()
  {
    return DataType< ::move_head::Head_position >::value();
  }
  static const char* value(const ::move_head::Head_positionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVE_HEAD_MESSAGE_HEAD_POSITION_H
